### ISSUE TITLE
Isn't this redundant?

### ISSUE THREAD

**Issue by vanthome** [darobin/web-schema#7]
Just a humble hint:
I had a similar requirement, wanted to generate forms out of JSON-Schema and validate but nothing I found was really satisfying (www.alpacajs.org, https://github.com/marianoguerra/json-edit) because all blend visual representation concerns with data model definition which I don't like but then I found this by chance and I really like it: https://github.com/joshfire/jsonform/wiki

**Comment by darobin** [comment]
Thanks for the hint! As it happens, I am well aware of jsonform, in fact not long ago I had a long evening of beers with its creator, François, to talk about how things can move forward.

The goal of Web Schema is to provide that and more, and also to support a form generation model that's more flexible than other existing options. We're definitely not there yet and progress is slow since it's a side-project, but if I get where I want to go it could very well be an option to somehow merge with jsonform.

In the meantime, definitely use jsonform, it's more mature and it works today!

**Comment by vanthome** [comment]
Great that you even know each other and thanks for your assessment.
